export const adminPage = `<!doctype html>
<html lang="uk">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#191920">
<meta name="robots" content="noindex,nofollow,noarchive">
<title>Замовлення | Літо 2014</title>
<style>
:root{--paper:#f4f1ea;--paper-deep:#eae5da;--ink:#191920;--muted:#74716b;--rule:#d7d0c3;--blue:#2f4a9a;--blue-weak:#e7ecf8;--plum:#29171f;--green:#286547;--amber:#a96e18;--red:#9e3a38;--serif:Georgia,'Times New Roman',serif;--sans:Arial,Helvetica,sans-serif}
*{box-sizing:border-box}html{background:var(--paper)}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.45 var(--sans);-webkit-font-smoothing:antialiased}
button,input,select{font:inherit}button{cursor:pointer}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid rgba(47,74,154,.25);outline-offset:2px}
.top{min-height:78px;background:var(--ink);color:var(--paper);display:flex;align-items:center}.wrap{width:min(1380px,100%);margin:0 auto;padding:0 32px}.top-in{display:flex;align-items:center;justify-content:space-between;gap:24px;padding-block:15px}.brand{display:flex;align-items:center;gap:14px;min-width:0}.mark{width:36px;height:36px;flex:0 0 36px;border:1px solid rgba(244,241,234,.72);border-radius:50%;position:relative}.mark:before,.mark:after{content:"";position:absolute;left:50%;top:50%;width:1px;height:27px;background:#9cafdf;transform:translate(-50%,-50%)}.mark:after{transform:translate(-50%,-50%) rotate(90deg)}.mark i{position:absolute;inset:10px;border:1px solid #9cafdf;border-radius:50%}.brand-copy{min-width:0}.brand-copy b{display:block;font-size:12px;letter-spacing:.18em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.brand-copy span{display:block;margin-top:2px;color:#bdb7ad;font:11px/1.3 var(--sans);letter-spacing:.12em;text-transform:uppercase}.session{color:#bdb7ad;font-size:12px;letter-spacing:.09em;text-transform:uppercase;white-space:nowrap}
main{padding:42px 0 72px}.masthead{display:flex;justify-content:space-between;align-items:end;gap:24px;padding-bottom:25px;border-bottom:1px solid var(--rule)}.eyebrow{margin:0 0 9px;color:var(--blue);font-size:11px;font-weight:700;letter-spacing:.18em;text-transform:uppercase}.masthead h1{margin:0;font:400 clamp(2rem,4vw,3.7rem)/.96 var(--serif);letter-spacing:0}.refresh{border:1px solid var(--ink);background:transparent;color:var(--ink);padding:11px 15px;font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;transition:background .18s,color .18s}.refresh:hover{background:var(--ink);color:var(--paper)}
.metrics{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid var(--rule)}.metric{padding:22px 20px 23px 0;border-right:1px solid var(--rule);min-width:0}.metric:not(:first-child){padding-left:20px}.metric:last-child{border-right:0}.metric span{display:block;color:var(--muted);font-size:10px;font-weight:700;letter-spacing:.17em;text-transform:uppercase}.metric strong{display:block;margin-top:6px;font:400 clamp(1.75rem,3vw,2.5rem)/1 var(--serif);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.metric strong.blue{color:var(--blue)}
.controls{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:22px;align-items:center;padding:25px 0 18px}.search{width:100%;height:46px;border:1px solid var(--rule);border-radius:0;background:rgba(255,255,255,.45);padding:0 14px;color:var(--ink)}.search::placeholder{color:#98938b}.filters{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.filter{border:1px solid transparent;background:transparent;padding:9px 10px;color:var(--muted);font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.filter:hover{border-color:var(--rule);color:var(--ink)}.filter.active{border-color:var(--blue);background:var(--blue);color:#fff}
.message{min-height:22px;margin:0 0 12px;color:var(--muted);font-size:13px}.message.error{color:var(--red)}.message.ok{color:var(--green)}
.orders{border-top:2px solid var(--ink)}.order{display:grid;grid-template-columns:minmax(165px,1.05fr) minmax(175px,1.25fr) minmax(210px,1.5fr) minmax(165px,1fr) minmax(180px,.95fr);gap:20px;align-items:start;padding:21px 0;border-bottom:1px solid var(--rule)}.order-top{min-width:0}.order-id{display:block;font-size:11px;font-weight:700;letter-spacing:.12em;color:var(--blue);overflow-wrap:anywhere}.order-date{display:block;margin-top:6px;color:var(--muted);font-size:12px}.status{display:inline-flex;align-items:center;gap:7px;margin-top:12px;color:var(--muted);font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.status:before{content:"";width:8px;height:8px;border-radius:50%;background:currentColor}.status.new{color:var(--amber)}.status.confirmed,.status.paid{color:var(--blue)}.status.shipped{color:var(--green)}.status.completed{color:#576254}.status.cancelled{color:var(--red)}
.customer b,.destination b{display:block;font-size:14px;line-height:1.35}.customer a{display:inline-block;margin-top:6px;color:var(--blue);font-size:13px;text-decoration-thickness:1px;text-underline-offset:3px}.customer small,.destination small{display:block;margin-top:3px;color:var(--muted);font-size:12px}.destination{min-width:0}.destination p{margin:7px 0 0;font-size:13px;line-height:1.4;overflow-wrap:anywhere}.money{font:400 1.45rem/1 var(--serif);white-space:nowrap}.money small{display:block;margin-top:7px;color:var(--muted);font:12px/1.3 var(--sans)}.manage{display:flex;gap:8px;align-items:stretch}.manage select{min-width:0;flex:1;height:40px;border:1px solid var(--rule);border-radius:0;background:#fff;color:var(--ink);padding:0 8px;font-size:12px}.save{height:40px;border:1px solid var(--blue);border-radius:0;background:var(--blue);color:#fff;padding:0 11px;font-size:11px;font-weight:700;letter-spacing:.06em;text-transform:uppercase;transition:background .18s}.save:hover{background:#22376f}.save:disabled{opacity:.55;cursor:wait}
.empty{padding:64px 0;border-bottom:1px solid var(--rule);font:400 1.55rem/1.25 var(--serif);color:var(--muted);text-align:center}.loading{padding:42px 0;border-bottom:1px solid var(--rule);color:var(--muted);font-size:13px;letter-spacing:.1em;text-transform:uppercase}.hidden{display:none!important}
@media(max-width:980px){.order{grid-template-columns:1fr 1.1fr 1.1fr}.money{grid-column:1/2}.manage{grid-column:2/4}.metrics{grid-template-columns:repeat(2,1fr)}.metric:nth-child(2){border-right:0}.metric:nth-child(n+3){border-top:1px solid var(--rule)}}
@media(max-width:640px){.wrap{padding:0 18px}.top-in{padding-block:13px}.session{display:none}main{padding:27px 0 48px}.masthead{align-items:start;flex-direction:column;gap:18px}.masthead h1{font-size:2.35rem}.refresh{width:100%}.metrics{grid-template-columns:1fr 1fr}.metric{padding:17px 12px 18px 0}.metric:not(:first-child){padding-left:12px}.metric strong{font-size:1.75rem}.controls{grid-template-columns:1fr;gap:13px;padding-top:19px}.filters{justify-content:flex-start}.filter{padding:9px 8px}.order{grid-template-columns:1fr;gap:14px;padding:20px 0}.money,.manage{grid-column:auto}.manage{max-width:100%}.save{padding-inline:15px}.customer b,.destination b{font-size:15px}.brand-copy span{font-size:10px}}
</style>
</head>
<body>
<header class="top"><div class="wrap top-in"><div class="brand"><span class="mark" aria-hidden="true"><i></i></span><span class="brand-copy"><b>Літо 2014</b><span>Кабінет замовлень</span></span></div><span class="session">Захищений доступ</span></div></header>
<main class="wrap">
  <section class="masthead"><div><p class="eyebrow">Контроль видання</p><h1>Замовлення</h1></div><button class="refresh" id="refresh" type="button">Оновити</button></section>
  <section class="metrics" aria-label="Статистика"><div class="metric"><span>Усього заявок</span><strong id="metric-orders">—</strong></div><div class="metric"><span>Нові</span><strong class="blue" id="metric-new">—</strong></div><div class="metric"><span>Книг</span><strong id="metric-books">—</strong></div><div class="metric"><span>Сума заявок</span><strong id="metric-revenue">—</strong></div></section>
  <section class="controls"><input class="search" id="search" type="search" autocomplete="off" placeholder="Пошук за ім’ям, телефоном, містом або номером замовлення" aria-label="Пошук замовлень"><nav class="filters" id="filters" aria-label="Статуси"><button class="filter active" type="button" data-filter="all">Усі</button><button class="filter" type="button" data-filter="new">Нові</button><button class="filter" type="button" data-filter="confirmed">Підтверджені</button><button class="filter" type="button" data-filter="paid">Оплачені</button><button class="filter" type="button" data-filter="shipped">Надіслані</button></nav></section>
  <p class="message" id="message" role="status" aria-live="polite"></p>
  <section class="orders" id="orders" aria-live="polite"><p class="loading">Завантажуємо замовлення</p></section>
</main>
<script>
(function(){
  var api=new URL('../api/admin/orders',window.location.href).toString();
  var statuses={new:'Нове',confirmed:'Підтверджено',paid:'Оплачено',shipped:'Надіслано',completed:'Завершено',cancelled:'Скасовано'};
  var orders=[];
  var activeFilter='all';
  var search=document.getElementById('search');
  var ordersNode=document.getElementById('orders');
  var message=document.getElementById('message');
  var money=new Intl.NumberFormat('uk-UA');

  function escapeHtml(value){return String(value==null?'':value).replace(/[&<>'"]/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]})}
  function formatDate(value){var date=new Date(value);return Number.isNaN(date.valueOf())?'—':new Intl.DateTimeFormat('uk-UA',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Kyiv'}).format(date)}
  function destination(order){if(order.deliveryMode==='abroad') return {title:'За кордон',detail:order.abroadAddress||'—'};return {title:order.deliveryMode==='parcel_locker'?'Поштомат НП':'Відділення НП',detail:(order.city||'—')+' · '+(order.deliveryPoint||'—')}}
  function statusOptions(current){return Object.keys(statuses).map(function(key){return '<option value="'+key+'"'+(key===current?' selected':'')+'>'+statuses[key]+'</option>'}).join('')}
  function setMessage(text,type){message.className='message'+(type?' '+type:'');message.textContent=text||''}
  function summary(items){return items.reduce(function(result,order){result.orders+=1;result.books+=Number(order.quantity)||0;result.revenue+=Number(order.total)||0;if(order.status==='new')result.newOrders+=1;return result},{orders:0,books:0,revenue:0,newOrders:0})}
  function renderMetrics(){var total=summary(orders);document.getElementById('metric-orders').textContent=money.format(total.orders);document.getElementById('metric-new').textContent=money.format(total.newOrders);document.getElementById('metric-books').textContent=money.format(total.books);document.getElementById('metric-revenue').textContent=money.format(total.revenue)+' ₴'}
  function matches(order,query){if(activeFilter!=='all'&&order.status!==activeFilter)return false;if(!query)return true;return [order.id,order.customerName,order.phone,order.city,order.deliveryPoint,order.abroadAddress].join(' ').toLocaleLowerCase('uk-UA').includes(query)}
  function render(){var query=search.value.trim().toLocaleLowerCase('uk-UA');var visible=orders.filter(function(order){return matches(order,query)});renderMetrics();if(!visible.length){ordersNode.innerHTML='<p class="empty">Замовлень за цим запитом немає.</p>';return}ordersNode.innerHTML=visible.map(function(order){var route=destination(order);var phone=escapeHtml(order.phone);return '<article class="order" data-id="'+escapeHtml(order.id)+'"><div class="order-top"><span class="order-id">'+escapeHtml(order.id)+'</span><span class="order-date">'+escapeHtml(formatDate(order.createdAt))+'</span><span class="status '+escapeHtml(order.status)+'">'+escapeHtml(statuses[order.status]||order.status)+'</span></div><div class="customer"><b>'+escapeHtml(order.customerName)+'</b><a href="tel:'+phone.replace(/[^+0-9]/g,'')+'">'+phone+'</a><small>'+escapeHtml(order.contactChannel||'')+'</small></div><div class="destination"><b>'+escapeHtml(route.title)+'</b><p>'+escapeHtml(route.detail)+'</p></div><div class="money">'+money.format(Number(order.total)||0)+' ₴<small>'+money.format(Number(order.quantity)||0)+' прим. '+(order.donation?' · донат '+money.format(Number(order.donation))+' ₴':'')+'</small></div><div class="manage"><select aria-label="Статус '+escapeHtml(order.id)+'">'+statusOptions(order.status)+'</select><button class="save" type="button" data-save>Зберегти</button></div></article>'}).join('')}
  function request(url,options){return fetch(url,Object.assign({credentials:'same-origin'},options||{})).then(function(response){return response.json().catch(function(){return {}}).then(function(data){if(!response.ok)throw new Error(data.error||'Не вдалося виконати запит.');return data})})}
  function load(){setMessage('');ordersNode.innerHTML='<p class="loading">Завантажуємо замовлення</p>';return request(api).then(function(data){orders=Array.isArray(data.orders)?data.orders.slice().sort(function(a,b){return new Date(b.createdAt)-new Date(a.createdAt)}):[];render()}).catch(function(error){orders=[];renderMetrics();ordersNode.innerHTML='<p class="empty">Дані зараз недоступні.</p>';setMessage(error.message,'error')})}
  document.getElementById('refresh').addEventListener('click',load);
  search.addEventListener('input',render);
  document.getElementById('filters').addEventListener('click',function(event){var button=event.target.closest('[data-filter]');if(!button)return;activeFilter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(function(item){item.classList.toggle('active',item===button)});render()});
  ordersNode.addEventListener('click',function(event){var button=event.target.closest('[data-save]');if(!button)return;var row=button.closest('[data-id]');var select=row.querySelector('select');var id=row.dataset.id;button.disabled=true;request(api+'/'+encodeURIComponent(id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:select.value})}).then(function(data){orders=orders.map(function(order){return order.id===data.order.id?data.order:order});setMessage('Статус збережено.','ok');render()}).catch(function(error){setMessage(error.message,'error')}).then(function(){button.disabled=false})});
  load();
})();
</script>
</body>
</html>`;
